# Copyright 2026 NXP

Layers:
  _model_23_Sub:
    Precision: INT16
  _model_23_Add_1:
    Precision: INT16
  _model_23_Add_2:
    Precision: INT16
  _model_23_Sub_1:
    Precision: INT16
  _model_23_Div_1:
    Precision: INT16
  _model_23_Concat_4:
    Precision: INT16
  _model_23_Mul_2:
    Precision: INT16
  _model_23_Sigmoid:
    Precision: INT16
