# Copyright 2026 NXP
#
# NXP Proprietary. This software is owned or controlled by NXP and may only be used strictly in accordance with the applicable license terms. By expressly accepting such terms or by downloading, installing, activating and/or otherwise using the software, you are agreeing that you have read, and that you agree to comply with and are bound by, such license terms. If you do not agree to be bound by the applicable license terms, then you may not retain, install, activate or otherwise use the software.

from pathlib import Path
from typing import Callable, List, Dict, Mapping

import numpy as np

from core.python.config import Config
from core.python.logger import logger
from core.python.inference import create_inference_session, ModelOutput
from core.python.inference.sessions.base import BaseInferenceSession
from core.python.inference.sessions.onnx_session import is_onnxruntime_available
from core.python.config import InferenceConfig

from ..utils import (
    align_shape_trailing_singletons,
    get_model_graph_continuation,
    map_device_to_continuation_nodes,
)


class ResolveInferenceOutputs:
    """
    Continue inference when the neural network graph has been truncated
    during on-device execution.

    ---------------------------------------------------------------------
    Overview
    ---------------------------------------------------------------------

    In certain ARA deployment scenarios, the accelerator cannot execute
    the full computation graph because some operators are unsupported.
    In such cases, the model graph is **cut off** at specific nodes and
    partially executed on-device.

    The device produces tensors corresponding to these intermediate
    graph nodes. This operator forwards those tensors to a **continuation
    graph** executed off-device (typically using FP32 precision) to
    complete the remaining computation.

    The continuation graph produces the final model predictions as a
    NumPy array.

    ---------------------------------------------------------------------
    Execution Context
    ---------------------------------------------------------------------

    • This operator is only active when a cut-off graph exists.
    • The continuation graph is loaded once during initialization
      and reused for each inference call.
    • Runtime execution is intentionally minimal to reduce latency
      during high-throughput inference pipelines.

    ---------------------------------------------------------------------
    Configuration Example
    ---------------------------------------------------------------------

    dvconvert:
        inode: images
        onode: /model.22/Mul_2_output_0:/model.22/Sigmoid_output_0

    ---------------------------------------------------------------------
    Input
    ---------------------------------------------------------------------

    input_data : ModelOutput
        Instance of `ModelOutput` containing outputs produced by the
        inference backend.

        When the model graph is executed in cut-off mode, these outputs
        correspond to the intermediate tensors generated by the on-device
        execution.

        `input_data.outputs` is a dictionary mapping output node names
        to NumPy arrays.

        Example:

            input_data.outputs = {
                "/model.22/Mul_2_output_0": np.ndarray(...),
                "/model.22/Sigmoid_output_0": np.ndarray(...),
            }

    ---------------------------------------------------------------------
    Output
    ---------------------------------------------------------------------

    ModelOutput
        Final model predictions wrapped in a `ModelOutput` interface instance.

        • If continuation inference is required (cut-off graph exists and
        backend is `"ara"`), the outputs from the device are forwarded to
        the continuation ONNX graph, and the resulting predictions are
        returned as a new `ModelOutput`.

        • If continuation inference is **not required**, the method returns
        the original `input_data` unchanged.

        The returned `ModelOutput.outputs` remains a dictionary mapping
        output node names to NumPy arrays.

        Example:

            result.outputs = {
                "output": np.ndarray(...),
            }

    ---------------------------------------------------------------------
    Example Usage
    ---------------------------------------------------------------------

    >>> resolver = ResolveInferenceOutputs(cfg, session_type="ara")
    >>> pipeline_payload["predictions"] = resolver.run_continuation_inference(input_data)
    >>> print(final_preds.shape)
    """

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    def __init__(self, cfg: "Config", session_type: str):
        """
        Initialize the graph continuation operator for cut-off ONNX model execution.

        Continuation inference is required when the on-device accelerator cannot
        execute the full computation graph. This class maps intermediate device
        outputs to the continuation graph inputs and validates the session.

        Parameters
        ----------
        cfg : object
            Pipeline configuration object containing:
            - `dvconvert` section with `onode` string defining device output nodes.
            - `out` attribute for output directory path.

        session_type : str
            Backend identifier. Continuation graph is executed only when this equals "ara".

        Attributes
        ----------
        continuation_model_path : Path
            Path to the ONNX continuation model file.

        cutoff_exists : bool
            True if continuation inference should be executed (session_type="ara" and
            continuation model exists); False otherwise.

        session : object
            Inference session object (if model exists and cutoff applies).

        device_to_continuation_map : Mapping[str, str]
            Dictionary mapping device output node names (keys) to continuation
            graph input node names (values). Used to prepare inputs for the continuation graph.

        num_device_onodes : int
            Number of device output nodes configured in `device_to_continuation_map`.

        onnx_input_shapes : Dict[str, tuple]
            Mapping from continuation graph input names to expected ONNX shapes,
            used to align device outputs before inference.

        Raises
        ------
        ValueError
            If cfg is None, output directory is missing, or onode_str contains no valid nodes.
        AttributeError
            If cfg does not contain required attributes (`out` or `dvconvert`).
        TypeError
            If cfg.dvconvert.onode is not a string.
        RuntimeError
            If continuation session creation fails, input metadata cannot be retrieved,
            or session inputs mismatch the configured continuation graph nodes.

        Notes
        -----
        - Continuation inference is skipped entirely if `session_type != "ara"`.
        - Validation ensures that all configured continuation inputs exist in the ONNX session,
        and no unexpected inputs are present.
        """
        # ------------------------
        # Validate configuration
        # ------------------------
        if cfg is None:
            raise ValueError("cfg must not be None.")

        self.cfg = cfg
        self.session_type = session_type

        # ------------------------
        # Prepare continuation model path
        # ------------------------
        out_dir = Path(cfg.out)
        if not out_dir.exists():
            raise ValueError(f"Output directory does not exist: {out_dir}")

        self.continuation_model_path = (
            out_dir / "compiled_model" / "postprocessing.onnx"
        )

        self.continuation_backend: str | None = None
        self.pytorch_continuation: (
            Callable[[ModelOutput, Config], ModelOutput] | None
        ) = None

        if self.session_type != "ara":
            self.cutoff_exists = False
            logger.debug(
                "Session type is '%s'; graph continuation is not required.",
                self.session_type,
            )
        elif is_onnxruntime_available() and self.continuation_model_path.is_file():
            # Dev extras install onnxruntime; clients without it use PyTorch.
            self.cutoff_exists = True
            self.continuation_backend = "onnx"
            logger.info("Using ONNX Runtime graph continuation.")
        else:
            try:
                self.pytorch_continuation = get_model_graph_continuation(cfg.modelname)
            except (
                ValueError,
                FileNotFoundError,
                ImportError,
                AttributeError,
                TypeError,
            ):
                self.cutoff_exists = False
                logger.info(
                    "No graph continuation is registered for '%s'; treating ARA "
                    "outputs as final model outputs.",
                    getattr(cfg, "modelname", "<unknown>"),
                )
            else:
                self.cutoff_exists = True
                self.continuation_backend = "pytorch"
                logger.info(
                    "Using PyTorch graph continuation for '%s'.",
                    getattr(cfg, "modelname", "<unknown>"),
                )

        # --------------------------------------------------------------
        # Initialize continuation session if cut-off exists
        # --------------------------------------------------------------
        if self.cutoff_exists:
            # ------------------------
            # Parse and sanitize device output node names
            # ------------------------
            onode_str = getattr(cfg.dvconvert, "onode", "")
            if not isinstance(onode_str, str):
                raise TypeError("cfg.dvconvert.onode must be a string.")

            # Map device node names to continuation graph input names
            self.device_to_continuation_map: Mapping[str, str] = (
                map_device_to_continuation_nodes(onode_str)
            )
            self.num_device_onodes: int = len(self.device_to_continuation_map)

            if self.continuation_backend == "onnx":
                infer_cfg_any = cfg.inference
                if infer_cfg_any is None:
                    raise ValueError(
                        "cfg.inference must be provided for continuation inference."
                    )

                if not isinstance(infer_cfg_any, InferenceConfig):
                    raise TypeError(
                        "cfg.inference must be of type InferenceConfig, got "
                        f"{type(infer_cfg_any).__name__}"
                    )

                infer_cfg: InferenceConfig = infer_cfg_any
                self.session: "BaseInferenceSession" = create_inference_session(
                    self.continuation_model_path, infer_cfg
                )

                try:
                    session_input_names: List[str] = list(self.session.input_names)
                except Exception as e:
                    raise RuntimeError(
                        "Failed to retrieve input node names from continuation session."
                    ) from e

                if not session_input_names:
                    raise RuntimeError("Continuation model contains no input nodes.")

                self.onnx_input_shapes = {
                    node.name: tuple(node.shape)
                    for node in self.session.get_input_metadata()
                }

                expected_inputs = set(self.device_to_continuation_map.values())
                actual_inputs = set(session_input_names)

                missing_inputs = expected_inputs - actual_inputs
                unexpected_inputs = actual_inputs - expected_inputs

                if missing_inputs or unexpected_inputs:
                    err_msg = (
                        "Mismatch between configured continuation graph nodes and "
                        "ONNX session inputs."
                    )
                    if missing_inputs:
                        err_msg += (
                            f" Missing expected inputs: {sorted(missing_inputs)}."
                        )
                    if unexpected_inputs:
                        err_msg += f" Unexpected inputs in session: {sorted(unexpected_inputs)}."
                    raise RuntimeError(err_msg)

    def run_continuation_inference(self, input_data: "ModelOutput") -> "ModelOutput":
        """
        Execute continuation inference for a cut-off ONNX model graph.

        If no cut-off graph exists or backend is not "ara", returns the
        first output from `input_data.outputs`.

        Parameters
        ----------
        input_data : ModelOutput
            Data to process. Must have an 'outputs' attribute of type dict[str, np.ndarray].

        Returns
        -------
        ModelOutput
            - If continuation inference is executed: a new ModelOutput containing
            the final predictions.
            - Otherwise: returns `input_data` unchanged.

        Raises
        ------
        TypeError
            If input_data does not have the expected 'outputs' dict.
        RuntimeError
            If required outputs are missing or continuation inference fails.
        ValueError
            If device output count mismatches configured nodes.
        KeyError
            If expected node names are missing in device outputs.
        """
        # ------------------------
        # Validate input_data
        # ------------------------
        if not hasattr(input_data, "outputs") or not isinstance(
            input_data.outputs, dict
        ):
            raise TypeError(
                f"Expected input_data to be a ModelOutput instance with an 'outputs' dict, "
                f"got {type(input_data).__name__}."
            )

        # ------------------------
        # Skip continuation if no cut-off graph or non-ARA backend
        # ------------------------
        if not self.cutoff_exists or self.session_type != "ara":
            if not input_data.outputs:
                raise RuntimeError(
                    "input_data.outputs is empty; cannot return any prediction."
                )

            return input_data

        # ------------------------
        # Prepare continuation inputs
        # ------------------------
        device_outputs: Dict[str, np.ndarray] = input_data.outputs

        if len(device_outputs) != self.num_device_onodes:
            raise ValueError(
                f"Mismatch between received device outputs ({len(device_outputs)}) "
                f"and configured device nodes ({self.num_device_onodes})."
            )

        if self.continuation_backend == "pytorch":
            if self.pytorch_continuation is None:
                raise RuntimeError("PyTorch continuation was selected but not loaded.")
            result = self.pytorch_continuation(input_data, self.cfg)
            if not isinstance(result, ModelOutput):
                raise TypeError(
                    "PyTorch continuation must return ModelOutput, got "
                    f"{type(result).__name__}."
                )
            if not result.outputs:
                raise RuntimeError(
                    "PyTorch continuation completed but returned no outputs."
                )
            return result

        if self.continuation_backend != "onnx":
            raise RuntimeError(
                f"Unsupported continuation backend: {self.continuation_backend}"
            )

        continuation_inputs: Dict[str, np.ndarray] = {}

        for device_onode, continuation_inode in self.device_to_continuation_map.items():
            array = device_outputs.get(device_onode)

            if array is None:
                raise KeyError(
                    f"Device output missing expected node '{device_onode}' "
                    f"required by continuation graph input '{continuation_inode}'."
                )

            continuation_inputs[continuation_inode] = array

        # ------------------------
        # Align input shapes
        # ------------------------
        for node_name, array in continuation_inputs.items():
            expected_shape = self.onnx_input_shapes[node_name]
            continuation_inputs[node_name] = align_shape_trailing_singletons(
                array, expected_shape
            )

        # ------------------------
        # Execute continuation graph
        # ------------------------
        result = self.session.infer(continuation_inputs)
        outputs = result.outputs

        # ------------------------
        # Validate outputs
        # ------------------------
        if not outputs:
            raise RuntimeError("Inference completed but returned no outputs.")

        return result
