modelname: "vit_base_patch16_224"
out: "../output"
precompiled_model_link_path: "./tmp/path/to/dvm"


network:
    srcfw: "onnx"
    inet: ../output/compiled_model/quantized_model.onnx
    iwt: ../output/compiled_model/quantized_model.onnx
    dim: "3,224,224"
    tags: null
    label: null
    pcfg: null
    images:
        quantize: ../output/preprocessed_images_quantize
        verify: ../output/preprocessed_images_verify


dvconvert:
    lname: null
    lshape: null
    np: False
    inode: "input_0"
    onode: "output_0"
    rsmax: False
    data_format: "CHW"
    ignore_mse: False
    state_name: null
    state_shape: null
    tg: True
    dynamic: false
    dynamic_input: false
    no_final_perm_opt: false
    dformat: null
    encodings_json_file: ../output/compiled_model/quantization_encodings.json


dvnc:
    layeroutput: False
    qmode: 9
    qonly: False
    bc: False
    adjust: null
    asymmetric: false
    clampqlimits: false
    use_tf_enhanced_encoding: false


inference:
    endpoint: 0
    interface: IPV4
    socket: "127.0.0.1:5000"


preprocess:
    input_shape:
        c: 3
        h: 224
        w: 224
    mean:
        r: 127.5
        g: 127.5
        b: 127.5
    scale:
        r: 0.00784313725
        g: 0.00784313725
        b: 0.00784313725
    resize:
        resize_size: 248
        aspect_ratio: True
        scale: 1
        interpolation: BICUBIC
        padding: null
    centercrop:
      h: 224
      w: 224
    bgr_to_rgb: True
    to_float: True
    hwc_to_chw: True


postprocess:
    tags: ../output/tags.txt
    label: ""
    image_overlay: True
    dump_output: False
    top_k: 10


calibration_data:
    image_url:
    quantize: ../output/quant
    verify: null
    quantize_list: null


evaluation:
    type: imagenet
    split: val


quantization:
    quantization_config: ./quantization_config.json
